qa/cephfs: cover the case when -k none provided
The teuthology-suite fails to schedule when -k none is provided
and terminate with error message:

    lupa.lua54.LuaError: [string "teuthology"]:3: attempt to index a nil value (local 'kernel')

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@clyso.com>
(cherry picked from commit 7bf01d6ddcdcff56ca977140d5a620d86fa76d01)