qa/tasks/nvme_loop: don't read scratch_devs twice
Address the error message when '/scratch_devs' file is missing:

    2026-01-19T18:43:18.014 DEBUG:teuthology.orchestra.run.vm01:> dd if=/scratch_devs of=/dev/stdout
    2026-01-19T18:43:18.068 DEBUG:teuthology.orchestra.run:got remote process result: 1
    2026-01-19T18:43:18.068 ERROR:teuthology.run_tasks:Saw exception from tasks.
    Traceback (most recent call last):
      File ".../teuthology/teuthology/run_tasks.py", line 112, in run_tasks
        manager.__enter__()
      File ".../.local/share/uv/python/cpython-3.10.19-linux-x86_64-gnu/lib/python3.10/contextlib.py", line 135, in __enter__
        return next(self.gen)
      File ".../src/.../qa/tasks/nvme_loop.py", line 66, in task
        old_scratch_by_remote[remote] = remote.read_file('/scratch_devs')
      File ".../teuthology/teuthology/orchestra/remote.py", line 258, in read_file
        raise FileNotFoundError(errno.ENOENT,
    FileNotFoundError: [Errno 2] Cannot find file on the remote 'ubuntu@vm01.local': '/scratch_devs'

The '/scratch_devs' already read a few lines of code above,
so just reuse 'devs' list recieved from get_scratch_devices().

Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@clyso.com>
(cherry picked from commit c840ffec125847ea817dd382b90ce3f47f627520)